well_commerce_deliverer:
    configuration:
        deliverer:
            orm:
                factory: WellCommerce\Bundle\DelivererBundle\Factory\DelivererFactory
                repository: WellCommerce\Bundle\DelivererBundle\Repository\DelivererRepository
                mapping: "@WellCommerceDelivererBundle/Resources/config/doctrine/Deliverer.orm.yml"
                entity: WellCommerce\Bundle\DelivererBundle\Entity\Deliverer
            api:
                exposed: true
                dataset: deliverer.dataset.admin
                manager: deliverer.manager
        deliverer_translation:
            orm:
                manager: false
                mapping: "@WellCommerceDelivererBundle/Resources/config/doctrine/DelivererTranslation.orm.yml"
                entity: WellCommerce\Bundle\DelivererBundle\Entity\DelivererTranslation

well_commerce_locale:
    copier:
        entities:
            WellCommerce\Bundle\DelivererBundle\Entity\DelivererTranslation:
                properties:
                    - name
