WellCommerce\Bundle\DelivererBundle\Entity\Deliverer:
    fields:
        id:
            groups:
                - default
                - deliverer
        createdAt:
            groups: {  }
        updatedAt:
            groups: {  }
    associations:
        producers:
            groups:
                - deliverer
        createdBy:
            groups:
                - deliverer
        updatedBy:
            groups:
                - deliverer
        deletedBy:
            groups:
                - deliverer
        translations:
            groups:
                - deliverer
    callbacks: {  }
